-- V1: Sprint-1 baseline — identity and audit schemas.
-- Conventions per docs/database/domain-model.md §I.1:
--   * uuid PKs (UUIDv7 generated by the application)
--   * audit columns (created_at/updated_at/created_by/updated_by/version) on business tables
--   * snake_case names, timestamptz everywhere
--   * schema per bounded context; cross-module table access forbidden in code (ArchUnit)
-- Requires privileges to CREATE EXTENSION (superuser locally / rds_superuser-equivalent).

CREATE EXTENSION IF NOT EXISTS citext;

CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS audit;

-- ============================================================================ identity

CREATE TABLE identity.user_account (
    id                uuid         PRIMARY KEY,
    email             citext       NOT NULL,
    password_hash     text         NOT NULL,
    display_name      varchar(120) NOT NULL,
    locale            varchar(16)  NOT NULL DEFAULT 'en',
    status            varchar(32)  NOT NULL,
    email_verified_at timestamptz,
    last_login_at     timestamptz,
    created_at        timestamptz  NOT NULL,
    updated_at        timestamptz  NOT NULL,
    created_by        uuid,
    updated_by        uuid,
    version           int          NOT NULL DEFAULT 0,
    CONSTRAINT uq_user_account_email UNIQUE (email),
    CONSTRAINT ck_user_account_status
        CHECK (status IN ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED'))
);

CREATE TABLE identity.email_verification_token (
    id         uuid        PRIMARY KEY,
    user_id    uuid        NOT NULL REFERENCES identity.user_account (id) ON DELETE CASCADE,
    token_hash varchar(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    used_at    timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by uuid,
    updated_by uuid,
    version    int         NOT NULL DEFAULT 0,
    CONSTRAINT uq_email_verification_token_hash UNIQUE (token_hash)
);

CREATE INDEX ix_email_verification_token_user_id
    ON identity.email_verification_token (user_id);

CREATE TABLE identity.refresh_token (
    id          uuid        PRIMARY KEY,
    user_id     uuid        NOT NULL REFERENCES identity.user_account (id) ON DELETE CASCADE,
    token_hash  varchar(64) NOT NULL,
    family_id   uuid        NOT NULL,
    expires_at  timestamptz NOT NULL,
    revoked_at  timestamptz,
    replaced_by uuid,
    created_at  timestamptz NOT NULL,
    updated_at  timestamptz NOT NULL,
    created_by  uuid,
    updated_by  uuid,
    version     int         NOT NULL DEFAULT 0,
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash)
);

CREATE INDEX ix_refresh_token_user_id ON identity.refresh_token (user_id);
-- Family revocation (logout, reuse/theft detection) updates by family.
CREATE INDEX ix_refresh_token_family_id ON identity.refresh_token (family_id);

-- Append-only; no audit columns or optimistic locking by design.
CREATE TABLE identity.login_attempt (
    id      uuid        PRIMARY KEY,
    user_id uuid,
    email   citext      NOT NULL,
    ip      varchar(45),
    outcome varchar(32) NOT NULL,
    at      timestamptz NOT NULL
);

-- Brute-force window queries: failures per email within the last 15 minutes.
CREATE INDEX ix_login_attempt_email_at ON identity.login_attempt (email, at DESC);

-- ============================================================================ audit

-- Append-only audit trail (partitioning by month deferred until volume requires it).
CREATE TABLE audit.audit_log (
    id             uuid         PRIMARY KEY,
    actor_user_id  uuid,
    action         varchar(100) NOT NULL,
    target_type    varchar(100),
    target_id      varchar(100),
    correlation_id varchar(64),
    at             timestamptz  NOT NULL
);

CREATE INDEX ix_audit_log_target ON audit.audit_log (target_type, target_id, at);
