-- V2: organizations bounded context — organizations, memberships, invitations.
-- Conventions per docs/database/domain-model.md §I.1 (see V1):
--   * uuid PKs (UUIDv7 generated by the application)
--   * audit columns (created_at/updated_at/created_by/updated_by/version) on business tables
--   * snake_case names, timestamptz everywhere
--   * schema per bounded context; cross-module table access forbidden in code (ArchUnit) —
--     FKs into identity are a database-level integrity net only.

CREATE SCHEMA IF NOT EXISTS organizations;

CREATE TABLE organizations.organization (
    id         uuid         PRIMARY KEY,
    name       varchar(120) NOT NULL,
    type       varchar(32)  NOT NULL,
    country    char(2),
    status     varchar(32)  NOT NULL DEFAULT 'ACTIVE',
    created_at timestamptz  NOT NULL,
    updated_at timestamptz  NOT NULL,
    created_by uuid,
    updated_by uuid,
    version    int          NOT NULL DEFAULT 0,
    CONSTRAINT ck_organization_type
        CHECK (type IN ('BUYER', 'SUPPLIER', 'HYBRID')),
    CONSTRAINT ck_organization_status
        CHECK (status IN ('ACTIVE', 'SUSPENDED')),
    CONSTRAINT ck_organization_country
        CHECK (country IS NULL OR country ~ '^[A-Z]{2}$')
);

-- REMOVED rows are terminal and retained for audit; re-joining creates a new row.
CREATE TABLE organizations.membership (
    id              uuid        PRIMARY KEY,
    organization_id uuid        NOT NULL REFERENCES organizations.organization (id),
    user_id         uuid        NOT NULL REFERENCES identity.user_account (id),
    role            varchar(32) NOT NULL,
    status          varchar(32) NOT NULL,
    joined_at       timestamptz NOT NULL,
    removed_at      timestamptz,
    created_at      timestamptz NOT NULL,
    updated_at      timestamptz NOT NULL,
    created_by      uuid,
    updated_by      uuid,
    version         int         NOT NULL DEFAULT 0,
    CONSTRAINT ck_membership_role
        CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER')),
    CONSTRAINT ck_membership_status
        CHECK (status IN ('ACTIVE', 'REMOVED'))
);

-- One ACTIVE membership per (organization, user); historical REMOVED rows may repeat.
CREATE UNIQUE INDEX uq_membership_active_org_user
    ON organizations.membership (organization_id, user_id)
    WHERE status = 'ACTIVE';

CREATE INDEX ix_membership_user_id ON organizations.membership (user_id);
CREATE INDEX ix_membership_organization_id ON organizations.membership (organization_id);

-- Only the SHA-256 hash of the single-use invitation token is stored.
CREATE TABLE organizations.invitation (
    id              uuid        PRIMARY KEY,
    organization_id uuid        NOT NULL REFERENCES organizations.organization (id),
    email           citext      NOT NULL,
    role            varchar(32) NOT NULL,
    token_hash      varchar(64) NOT NULL,
    status          varchar(32) NOT NULL,
    invited_by      uuid        NOT NULL REFERENCES identity.user_account (id),
    expires_at      timestamptz NOT NULL,
    accepted_at     timestamptz,
    accepted_by     uuid        REFERENCES identity.user_account (id),
    created_at      timestamptz NOT NULL,
    updated_at      timestamptz NOT NULL,
    created_by      uuid,
    updated_by      uuid,
    version         int         NOT NULL DEFAULT 0,
    CONSTRAINT uq_invitation_token_hash UNIQUE (token_hash),
    -- OWNER cannot be invited; promote after joining.
    CONSTRAINT ck_invitation_role
        CHECK (role IN ('ADMIN', 'MEMBER')),
    CONSTRAINT ck_invitation_status
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED'))
);

-- One PENDING invitation per (organization, email); email is citext, so case-insensitive.
CREATE UNIQUE INDEX uq_invitation_pending_org_email
    ON organizations.invitation (organization_id, email)
    WHERE status = 'PENDING';

CREATE INDEX ix_invitation_organization_id ON organizations.invitation (organization_id);
